/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TRANSFERFILE_H_RPCGEN
#define _TRANSFERFILE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXFILE 1024

typedef char *filename;

typedef char fileContent[MAXFILE];

struct transferFile_in {
	filename name;
	int size;
	fileContent data;
};
typedef struct transferFile_in transferFile_in;

struct transferFile_out {
	long sucess;
};
typedef struct transferFile_out transferFile_out;

#define TRANSFERFILE_PROG 0x31230000
#define TRANSFERFILE_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define transfer_file 1
extern  transferFile_out * transfer_file_1(transferFile_in *, CLIENT *);
extern  transferFile_out * transfer_file_1_svc(transferFile_in *, struct svc_req *);
extern int transferfile_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define transfer_file 1
extern  transferFile_out * transfer_file_1();
extern  transferFile_out * transfer_file_1_svc();
extern int transferfile_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_filename (XDR *, filename*);
extern  bool_t xdr_fileContent (XDR *, fileContent);
extern  bool_t xdr_transferFile_in (XDR *, transferFile_in*);
extern  bool_t xdr_transferFile_out (XDR *, transferFile_out*);

#else /* K&R C */
extern bool_t xdr_filename ();
extern bool_t xdr_fileContent ();
extern bool_t xdr_transferFile_in ();
extern bool_t xdr_transferFile_out ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_TRANSFERFILE_H_RPCGEN */
