/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "transferFile.h"

bool_t
xdr_filename (XDR *xdrs, filename *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, 1024))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_fileContent (XDR *xdrs, fileContent objp)
{
	register int32_t *buf;

	 if (!xdr_opaque (xdrs, objp, MAXFILE))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_transferFile_in (XDR *xdrs, transferFile_in *objp)
{
	register int32_t *buf;

	 if (!xdr_filename (xdrs, &objp->name))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->size))
		 return FALSE;
	 if (!xdr_fileContent (xdrs, objp->data))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_transferFile_out (XDR *xdrs, transferFile_out *objp)
{
	register int32_t *buf;

	 if (!xdr_long (xdrs, &objp->sucess))
		 return FALSE;
	return TRUE;
}
