/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "transferFile.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

transferFile_out *
transfer_file_1(transferFile_in *argp, CLIENT *clnt)
{
	static transferFile_out clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, transfer_file,
		(xdrproc_t) xdr_transferFile_in, (caddr_t) argp,
		(xdrproc_t) xdr_transferFile_out, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
